### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jburkhardt** [banboo-data/r4googleads#19]
Clarify which open source license is most appropriate?

**Comment by mbannert** [comment]
https://r-pkgs.org/license.html

and

https://thinkr-open.github.io/licensing-r/

What's interesting (from Hadley): " Note that simply using a package or R itself **doesn’t** require that you comply with the license; this is why you can write proprietary R code and why R packages can have any license you choose."

-> I would love to have a explanation for this. I'll read this up and when I doubt tweet Hadley. Even if he doesn't answer, chances are we get a good answer from somebody else. But it does make sense given that there are non copy-left licenses on CRAN. 

-> I am on it, report back here when I have a suggestion.

**Comment by mbannert** [comment]
Important note on Re-licensing (changing the license later on): 

"It’s important to spend a little time thinking about your initial license because it can be hard to change it later because it requires the permission of all copyright holders. Unless you’ve done something special (which we’ll discuss in Section 9.3), the copyright holders include everyone who has contributed a non-trivial amount of code."

-> be careful accepting PRs.

**Comment by mbannert** [comment]
FWIW, Python does not have all this GPL mess:
https://www.python.org/download/releases/3.4.0/license/
